//Enthusiasm constants
export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


//Form Constants
export const UPDATE_FORM_FIELD = 'UPDATE_FORM_FIELD';
export type UPDATE_FORM_FIELD = typeof UPDATE_FORM_FIELD;

export const CLEAR_FORM = 'CLEAR_FORM';
export type CLEAR_FORM = typeof CLEAR_FORM;